<a href="https://colab.research.google.com/github/Timixojo/Timixojo/blob/main/Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
#import pandas to Google Colab

import pandas as pd


In [ ]:
#using a very big dataset,
#download California datasets file from Github

In [ ]:
#load California training datasets to Google Colab

df_train=pd.read_csv("/content/california_housing_train.csv")

df_train

In [ ]:
#do the same for testing datasets

df_test=pd.read_csv("/content/california_housing_test.csv")

df_test

In [12]:
#define data to use for training and testing.

In [ ]:
#define for x_train and y_train

x_train=df_train.loc[:,['housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income']]

y_train=df_train.loc[:,['median_house_value']]

#x_train
y_train


In [ ]:
#do the same for x_test and y_test

x_test=df_test.loc[:,['housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income']]

y_test=df_test.loc[:,['median_house_value']]

#x_test
y_test

In [ ]:
#Implementing Decision Tree Regression to evaluate datasets

In [35]:
#Decision Tree Regression

#train DT model

from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(x_train, y_train)

DecisionTreeRegressor()

In [37]:
#create a model to predict test data

y_predict=model.predict(x_test)

y_predict

array([287800., 109500., 307100., ..., 114600., 156300., 500001.])

In [ ]:
#using evaluation metrics to test the model

from sklearn import metrics
import numpy as np

print('Mean Squared Error: ', metrics.mean_squared_error(y_test, y_predict))
print('Mean Absolute Error: ', metrics.mean_absolute_error(y_test, y_predict))
print('Root Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(y_test, y_predict)))

In [ ]:
#Implementing Random Forest Regression to evaluate datasets

In [54]:
#Random Forest Regression

#train Randon Forest model

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators = 200)
model.fit(x_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(n_estimators=200)

In [55]:
#create a model to predict test data

y_predict=model.predict(x_test)

y_predict

array([372524.59 , 169592.   , 293262.515, ..., 116379.   , 167222.065,
       489982.85 ])

In [56]:
#using evaluation metrics to test the model

print('Mean Squared Root: ', metrics.mean_squared_error(y_test, y_predict))
print('Mean Absolute Error: ', metrics.mean_absolute_error(y_test, y_predict))
print('Root Mean Squared Error: ', np.sqrt(metrics.root_mean_squared_error(y_test, y_predict)))


Mean Squared Root:  4584528849.140836
Mean Absolute Error:  48510.96752499999
Root Mean Squared Error:  260.2098171328916


In [ ]:
#Implementing Linear Regression to evaluate datasets

In [57]:
#Linear Regression

#train Linear Regression model

from sklearn.linear_model import LinearRegression
model_LR=LinearRegression()
model_LR.fit(x_train, y_train)

LinearRegression()

In [61]:
#create a model to predict test data

y_predict=model_LR.predict(x_test)

y_predict

array([[332098.0230497 ],
       [213719.81431062],
       [271260.04407687],
       ...,
       [ 85797.18665274],
       [184332.1842798 ],
       [440203.98512845]])

In [66]:
#using evaluation metrics to test the model

print('Mean Squared Error: ', metrics.mean_squared_error(y_test, y_predict))
print('Mean Absolute Error: ', metrics.mean_absolute_error(y_test, y_predict))
print('Root Mean Squared Error: ', np.sqrt(metrics.root_mean_squared_error(y_test, y_predict)))

Mean Squared Error:  5808966246.7101965
Mean Absolute Error:  55396.294616990475
Root Mean Squared Error:  276.07349495989524


In [ ]:
#Implementing Support Vector Regression to evaluate datasets

In [67]:
#Support Vector Regression

#Train SVR model

from sklearn.svm import SVR
model = SVR(kernel = 'linear')
model.fit(x_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(kernel='linear')

In [69]:
#create a model to predict test data

y_predict=model.predict(x_test)

y_predict

array([254082.90354013, 200441.03245663, 239169.11554716, ...,
       128868.55187829, 183900.90403289, 275725.90487503])

In [72]:
#using evaluation metrics to test the model

print('Mean Squared Error: ', metrics.mean_squared_error(y_test, y_predict))
print('Mean Absolute Error: ', metrics.mean_absolute_error(y_test, y_predict))
print('Root Mean Squared Error: ', np.sqrt(metrics.root_mean_squared_error(y_test, y_predict)))

Mean Squared Error:  8674170898.750322
Mean Absolute Error:  69888.68160817654
Root Mean Squared Error:  305.1806499369257
